source 'https://github.com/CocoaPods/Specs.git'

platform :ios, :deployment_target => "7.0"

target 'UHNCGMController', :exclusive => true do
  pod "UHNCGMController", :path => "../"

  pod 'NHArrowView'
  pod 'UHNTimeSeriesPlotView'
end

target 'Tests', :exclusive => true do
  pod "UHNCGMController", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'OCMockito'
end
