source 'https://github.com/CocoaPods/Specs.git'

target 'UHNCGMController', :exclusive => true do
  pod "UHNCGMController", :path => "../"
  pod "NHArrowView"
  pod "UHNTimeSeriesPlotView"
end

target 'Tests', :exclusive => true do
  pod "UHNCGMController", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'OCMockito'
end
